### ISSUE TITLE
GraphiQL doesn't work with Mirconaut 2.0.0-M3

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-graphql#42]
When visiting http://localhost:8080/graphiql in my project I get the error below

>14:36:34.592 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: io.micronaut.context.env.DefaultPropertyPlaceholderResolver.<init>(Lio/micronaut/core/value/PropertyResolver;)V
java.lang.NoSuchMethodError: io.micronaut.context.env.DefaultPropertyPlaceholderResolver.<init>(Lio/micronaut/core/value/PropertyResolver;)V
        at io.micronaut.configuration.graphql.GraphiQLController.replaceParameters(GraphiQLController.java:123)
        at io.micronaut.configuration.graphql.GraphiQLController.resolvedTemplate(GraphiQLController.java:116)
        at io.micronaut.core.async.SupplierUtil$1.initialize(SupplierUtil.java:47)
        at io.micronaut.core.async.SupplierUtil$1.get(SupplierUtil.java:42)
        at io.micronaut.configuration.graphql.GraphiQLController.get(GraphiQLController.java:88)
        at io.micronaut.configuration.graphql.$GraphiQLControllerDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:457)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:255)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:117)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$11(RoutingInBoundHandler.java:1322)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.tracing.instrument.util.TracingPublisher.subscribe(TracingPublisher.java:120)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$5(RoutingInBoundHandler.java:1026)
        at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:81)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:117)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:687)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:549)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:144)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

**Comment by marceloverdijk** [comment]
I fixed this in the upcoming Micronaut-GraphQL `1.3.0` release.

**Comment by benmccann** [comment]
Thanks!

This may be a stupid question, but where is the Micronaut-GraphQL version specified? My build file just has `implementation("io.micronaut.graphql:micronaut-graphql")`. Is this a built-in feature of Gradle that means just use the latest version? Or does Micronaut core provide the version somewhere?

**Comment by marceloverdijk** [comment]
The Micronaut-GraphQL is part of the Micronaut BOM.
As you can see [here](https://github.com/micronaut-projects/micronaut-core/blob/v1.3.4/gradle.properties#L60) it is currently linked to `1.2.2`.

So when Micronaut-GraphQL `1.3.0` is synced to Maven Central and you want to use it you have to specify this version explicitly like `implementation("io.micronaut.graphql:micronaut-graphql:1.3.0")`.

With the next version of  released of Micronaut we will set the BOM version to `1.3.0`.

**Comment by benmccann** [comment]
Thanks!!

**Comment by benmccann** [comment]
I tried with 1.3.0 and am getting a couple errors:

```
Caused by: java.lang.IllegalArgumentException: Unsupported Reactive type: class io.micronaut.tracing.instrument.util.ScopePropagationPublisher
        at io.micronaut.core.async.publisher.Publishers.lambda$convertPublisher$8(Publishers.java:324)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.micronaut.core.async.publisher.Publishers.convertPublisher(Publishers.java:324)
        at io.micronaut.tracing.instrument.util.TracingPublisher$1.onNext(TracingPublisher.java:148)
        at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
        at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:67)
        at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
        at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
        at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:87)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:56)
        at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)

```

```
13:33:00.287 [nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: io.micronaut.context.env.DefaultPropertyPlaceholderResolver.<init>(Lio/micronaut/core/value/PropertyResolver;)V
java.lang.NoSuchMethodError: io.micronaut.context.env.DefaultPropertyPlaceholderResolver.<init>(Lio/micronaut/core/value/PropertyResolver;)V
        at io.micronaut.configuration.graphql.GraphiQLController.replaceParameters(GraphiQLController.java:123)
        at io.micronaut.configuration.graphql.GraphiQLController.resolvedTemplate(GraphiQLController.java:116)
        at io.micronaut.core.async.SupplierUtil$1.initialize(SupplierUtil.java:47)
        at io.micronaut.core.async.SupplierUtil$1.get(SupplierUtil.java:42)
        at io.micronaut.configuration.graphql.GraphiQLController.get(GraphiQLController.java:88)
        at io.micronaut.configuration.graphql.$GraphiQLControllerDefinition$$exec1.invokeInternal(Unknown Source)
```

The first error might be from `tracing-jaeger` or something, but the second one looks like it's from graphql

**Comment by benmccann** [comment]
I can't reproduce outside my project. It seems like it might be some issue with incompatible jars on my classpath or something. I'll wait until Micronaut 2.0.0-M4 comes out and then test again
